name: Terraform CI/CD

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  id-token: write
  contents: read
  pull-requests: read

jobs:

  terraform-plan:
    name: Terraform Plan
    if: github.ref != 'refs/heads/main'
    runs-on: self-hosted

    defaults:
      run:
        working-directory: environments/preprod

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan


  terraform-apply:
    name: Terraform Apply
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted

    defaults:
      run:
        working-directory: environments/preprod

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve